#ifndef QTSHADOWSOCKS_GLOBAL_H
#define QTSHADOWSOCKS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QTSHADOWSOCKS_LIBRARY
#  define QTSHADOWSOCKS_EXPORT Q_DECL_EXPORT
#else
#  define QTSHADOWSOCKS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSHADOWSOCKS_GLOBAL_H
